

# This file was *autogenerated* from the file inverse_light_mds_L4m.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3)# ****************************************************************************
#  Comput inverses of explicit constructions of MDS rot-add diffusion 
#  layers in three cases
#  Baofeng Wu, Aug 2025
# ****************************************************************************

from textwrap import fill


def get_data(file_path):
    data = []
    with open(file_path, 'r') as f:
        content = f.readlines()
        for line in content[_sage_const_4 ::_sage_const_2 ]:
            line_data = line.split('│ ')
            line_data = [x.strip() for x in line_data]
            line_data.remove('')
            line_data[_sage_const_2 ] = line_data[_sage_const_2 ].strip('│').strip()
            data.append(line_data)

    return data


files = {
    'Case 2': 'results/constructions_mds_L4m_Case 2.txt',
    'Case 4': 'results/constructions_mds_L4m_Case 4.txt',
    'Case 12': 'results/constructions_mds_L4m_Case 12.txt'
}
coefficients = {
    'Case 2': [-_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 ],
    'Case 4': [_sage_const_1 , _sage_const_1 , -_sage_const_1 , _sage_const_1 , _sage_const_1 ],
    'Case 12': [_sage_const_1 , -_sage_const_1 , _sage_const_1 , -_sage_const_1 , _sage_const_1 ]
}
R = QQ['x']; (x,) = R._first_ngens(1)

for case, file in files.items():
    try:
        all_data = get_data(file)
    except FileNotFoundError:
        print(f'File {file} not found. Run construct ... first.')
        continue

    result = []
    poly_width = _sage_const_0 
    for data in all_data:
        t = int(data[_sage_const_0 ].split('|')[_sage_const_0 ])
        k = data[_sage_const_1 ].split('m')[_sage_const_0 ]
        if not k:
            k = _sage_const_1 
        else:
            k = int(k)

        if data[_sage_const_2 ] == '--':
            result.append(data[:_sage_const_2 ] + ['--'])
        else:
            c = coefficients[case]
            poly = c[_sage_const_0 ] + c[_sage_const_1 ]*x**(k) + c[_sage_const_2 ]*x**(k+t) + c[_sage_const_3 ]*x**(k+_sage_const_2 *t) + c[_sage_const_4 ]*x**(_sage_const_3 *t)
            mod_poly = x**(_sage_const_4 *t) - _sage_const_1 
            inv_poly = poly.inverse_mod(mod_poly)
            poly_width = max(poly_width, len(str(inv_poly)))
            result.append(data[:_sage_const_2 ] + [inv_poly])

    with open(f'results/inverses_mds_L4m_{case}.txt', 'w') as f:
        f.write(f'Inverses of example constructions in {case},\n')
        f.write(f'represented by inverse associated poly.\n\n')
        header = [
            "condition t|m",
            "g2=km/t",
            "f(x) s.t. inverse = f(x^(m/t))".ljust(poly_width)
        ]
        result = table(result, header_row=header, frame=True)
        f.write(str(result))

    print(f'Results saved to: results/inverses_mds_L4m_{case}.txt')


